name: Build siyuan-android

on:
  push:
    branch: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '^1.23'
    - name: get kernel.aar
      run: |
        cp signings.templates.gradle  signings.gradle
        gh release download $TAG --repo $USER/$REPO --pattern "kernel.aar"
        sudo mkdir -p /home/runner/work/siyuan-android/siyuan-android/app/libs/
        sudo mkdir -p /home/runner/work/siyuan-android/siyuan-android/app/
        sudo mv kernel.aar /home/runner/work/siyuan-android/siyuan-android/app/libs/
        sudo mv siyuan-android.jks /home/runner/work/siyuan-android/siyuan-android/app/
      env:
        GITHUB_TOKEN: ${{ secrets.TK }}
        USER: john4650-hub
        REPO: siyuan-android
        TAG: "25.0.0"
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: |
        gradle clean buildReleaseTask #sudo apt-get -y install android-sdk-build-tools /curl -LO https://github.com/John4650-hub/siyuan-android/releases/download/217.0.0/siyuan-3.1.14-official-release.apk (aapt dump badging siyuan-3.1.14-official-release.apk) > details.txt gh release create "${{ github.run_number }}.0.0" details.txt 
        gh release create "${{ github.run_number }}.0.0" app/build-release/siyuan-3.1.14-all/*
      env:
        GITHUB_TOKEN: ${{ secrets.TK }}
