name: Build siyuan-android

on:
  push:
    branch: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '^1.23'
    - name: get kernel.aar
      run: |
        gh release download $TAG --repo $USER/$REPO --pattern "kernel.aar"
        sudo mkdir -p /home/runner/work/siyuan-android/siyuan-android/app/libs/
        sudo mkdir -p /home/runner/work/siyuan-android/siyuan-android/app/
        sudo mv kernel.aar /home/runner/work/siyuan-android/siyuan-android/app/libs/
        sudo siyuan-android.jks /home/runner/work/siyuan-android/siyuan-android/app/

      env:
        GITHUB_TOKEN: ${{ secrets.TK }}
        USER: john4650-hub
        REPO: siyuan-android
        TAG: "25.0.0"
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Configure app
      run: |
        gh release create ${{ github.run_number }}.0.0 /home/runner/work/siyuan-android/siyuan-android/app/libs/kernel.aar
        cp signings.templates.gradle  signings.gradle
      env:
        GH_TOKEN: ${{ secrets.TK }}


    - name: Build with Gradle
      run: gradle clean buildReleaseTask
