name: Build siyuan-android

on:
  push:
    branch: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Configure app
      run: |
        cp signings.templates.gradle  signings.gradle
    - name: Build with Gradle
      run: gradle clean buildReleaseTask
