name: Build siyuan-android

on:
  push:
    branch: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '^1.23'

    - name: Install Gomobile
      run: |
        gh repo clone siyuan-note/siyuan
        cd siyuan
        git checkout dev
        echo "CGO_ENABLED=1" >> $GITHUB_ENV
        curl -LO https://raw.githubusercontent.com/jerson/rsa-mobile/refs/heads/master/go.mod
        go install golang.org/x/mobile/cmd/gomobile@latest
        go install golang.org/x/mobile/cmd/gobind@latest
        go get golang.org/x/mobile/cmd/gomobile
        go get golang.org/x/mobile/cmd/gobind
        gomobile init
      env:
        GOPROXY: https://proxy.golang.org,direct
        GH_TOKEN: ${{ secrets.TK }}
        GO111MODULE: "on"
    - name: build kernel.aar
      run: |
        cd siyuan
        git checkout dev
        echo "CGO_ENABLED=1" >> $GITHUB_ENV
        ls -a
        cd kernel
        gomobile bind --tags fts5 -ldflags '-s -w' -v -o kernel.aar -target='android/arm64' -androidapi 23 ./mobile/
        ls -a
        gh release create ${{ github.run_number }}.0.0 kernel.aar
        mv kernel.aar /home/runner/work/siyuan-android/siyuan-android/app/libs/
      env:
        GH_TOKEN: ${{ secrets.TK }}
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Configure app
      run: |
        cp signings.templates.gradle  signings.gradle
    - name: Build with Gradle
      run: gradle clean buildReleaseTask
