name: Build siyuan-android

on:
  push:
    branch: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: setup gomobile
      run: |
        go install golang.org/x/mobile/cmd/gomobile@latest
        gomobile init
    - name: setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '^1.13.1'
    - name: build kernel.aar
      run: |
        gh repo clone siyuan-note/siyuan
        cd siyuan
        git checkout dev
        echo "CGO_ENABLED=1" >> $GITHUB_ENV
        ls -a
        cd kernel
        gomobile bind --tags fts5 -ldflags '-s -w' -v -o kernel.aar -target='android/arm64' -androidapi 23 ./mobile/
        ls -a
      env:
        GH_TOKEN: ${{ secrets.TK }}
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Configure app
      run: |
        cp signings.templates.gradle  signings.gradle
    - name: Build with Gradle
      run: gradle clean buildReleaseTask
